---
all:
  children:
    servers:
      hosts:
        k3s-master-1:
          ansible_host: 192.168.1.50
          k3s_role: server
          k3s_init: true  # First node bootstraps the cluster
        k3s-master-2:
          ansible_host: 192.168.1.51
          k3s_role: server
        k3s-master-3:
          ansible_host: 192.168.1.52
          k3s_role: server
    agents:
      hosts:
        k3s-worker-1:
          ansible_host: 192.168.1.53
          k3s_role: agent
          k3s_node_labels:
            - "node-role.kubernetes.io/worker=true"
            - "workload-type=on-demand"
          k3s_node_taints:
            - "on-demand=true:NoSchedule"
    pve:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_k3s
        loki_push_url: "https://loki.tmf-solutions.com/loki/api/v1/push"
        promtail_version: "3.5.1"
      hosts:
        pve01:
          ansible_host: 192.168.1.10
        pve02:
          ansible_host: 192.168.1.11
        pve03:
          ansible_host: 192.168.1.12
        pve04:
          ansible_host: 192.168.1.13
