---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ddns
              image: oznu/cloudflare-ddns:latest
              env:
                - name: CF_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-token
                      key: cloudflare-token
                - name: ZONE
                  value: "tmf-solutions.com"
                - name: SUBDOMAIN
                  value: "@"
                - name: PROXIED
                  value: "false"
              resources:
                requests:
                  memory: 16Mi
                  cpu: 10m
                limits:
                  memory: 32Mi
                  cpu: 50m
