---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jenkins.tmf-solutions.com`)
      kind: Rule
      services:
        - name: jenkins
          port: 8080
  tls: {}  # uses TLSStore default — wildcard cert from traefik namespace
