---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  namespace: monitoring
  labels:
    app: prometheus-pve-exporter
spec:
  selector:
    app: prometheus-pve-exporter
  ports:
    - name: metrics
      port: 9221
      targetPort: 9221
